import type { Metadata } from "next";
import { Roboto } from "next/font/google";
//전역 css
import "./styles/globals.css";
import SideNavigation from "@/components/common/navigation/SideNavigation";

const roboto = Roboto({ subsets: ["latin"],weight:["400","500","700"] });


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body   className={roboto.className} > 
        <SideNavigation/>
        {children}</body>
    </html>
  );
}
